name: Python CI

on:
  pull_request:
    branches:
      - main
      - dev
env:
  UV_SYSTEM_PYTHON: 1

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      # Get the repository content
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: ${{ matrix.python-version }}


      # Install dependencies
      - name: Install requirements
        run: |
          uv pip install -r requirements-dev.txt

      # Check code style
      - name: Run flake8
        run: flake8 src

      # Check type annotations
      - name: Run mypy
        run: uv run mypy src

      # Run unit tests
      - name: Run tests
        run: uv run pytest tests
